"""add appointment management

Revision ID: a1b358e7fc55
Revises: a35a3b728bfd
Create Date: 2026-08-13 15:18:45.572823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a1b358e7fc55'

down_revision: Union[str, Sequence[str], None] = 'a35a3b728bfd'

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_appointment_slots_appointment_id', 'appointment_slots', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointment_slots_appointment_id', 'appointment_slots', type_='foreignkey')
    # ### end Alembic commands ###