"""add appointment management

Revision ID: a35a3b728bfd
Revises: 20260811_0002
Create Date: 2026-08-13 15:02:06.018024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a35a3b728bfd'

down_revision: Union[str, Sequence[str], None] = '20260811_0002'

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_appointment_slots_appointment_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'slot_date', 'start_time', name='uq_doctor_slot')
    )
    op.create_index('ix_appointment_slot_lookup', 'appointment_slots', ['doctor_id', 'slot_date', 'is_available', 'is_blocked'], unique=False)
    op.create_index(op.f('ix_appointment_slots_appointment_id'), 'appointment_slots', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_slots_doctor_id'), 'appointment_slots', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_slots_is_available'), 'appointment_slots', ['is_available'], unique=False)
    op.create_index(op.f('ix_appointment_slots_is_blocked'), 'appointment_slots', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_appointment_slots_slot_date'), 'appointment_slots', ['slot_date'], unique=False)
    op.create_table('doctor_availability',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', 'start_time', 'end_time', name='uq_doctor_availability_period')
    )
    op.create_index(op.f('ix_doctor_availability_day_of_week'), 'doctor_availability', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_doctor_availability_doctor_id'), 'doctor_availability', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_availability_is_active'), 'doctor_availability', ['is_active'], unique=False)
    op.create_index('ix_doctor_availability_lookup', 'doctor_availability', ['doctor_id', 'day_of_week', 'is_active'], unique=False)
    op.create_table('appointment_waiting_list',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_start_time', sa.Time(), nullable=True),
    sa.Column('preferred_end_time', sa.Time(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_waiting_list_doctor_id'), 'appointment_waiting_list', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_waiting_list_patient_id'), 'appointment_waiting_list', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_waiting_list_preferred_date'), 'appointment_waiting_list', ['preferred_date'], unique=False)
    op.create_index(op.f('ix_appointment_waiting_list_status'), 'appointment_waiting_list', ['status'], unique=False)
    op.create_index('ix_waiting_list_doctor_date_status', 'appointment_waiting_list', ['doctor_id', 'preferred_date', 'status'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appointment_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.BigInteger(), nullable=True),
    sa.Column('appointment_type', sa.String(length=30), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('booking_source', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('parent_appointment_id', sa.BigInteger(), nullable=True),
    sa.Column('rescheduled_from_id', sa.BigInteger(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('consultation_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('no_show_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=True)
    op.create_index(op.f('ix_appointments_appointment_type'), 'appointments', ['appointment_type'], unique=False)
    op.create_index(op.f('ix_appointments_booking_source'), 'appointments', ['booking_source'], unique=False)
    op.create_index(op.f('ix_appointments_created_by'), 'appointments', ['created_by'], unique=False)
    op.create_index('ix_appointments_doctor_date', 'appointments', ['doctor_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_parent_appointment_id'), 'appointments', ['parent_appointment_id'], unique=False)
    op.create_index('ix_appointments_patient_date', 'appointments', ['patient_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_rescheduled_from_id'), 'appointments', ['rescheduled_from_id'], unique=False)
    op.create_index(op.f('ix_appointments_slot_id'), 'appointments', ['slot_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_status_date', 'appointments', ['status', 'appointment_date'], unique=False)
    op.create_table('appointment_reminders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_reminder_schedule', 'appointment_reminders', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_appointment_id'), 'appointment_reminders', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_scheduled_at'), 'appointment_reminders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_appointment_reminders_status'), 'appointment_reminders', ['status'], unique=False)
    op.create_table('appointment_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_history_appointment_status', 'appointment_status_history', ['appointment_id', 'new_status'], unique=False)
    op.create_index(op.f('ix_appointment_status_history_appointment_id'), 'appointment_status_history', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_status_history_changed_by'), 'appointment_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_appointment_status_history_new_status'), 'appointment_status_history', ['new_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_status_history_new_status'), table_name='appointment_status_history')
    op.drop_index(op.f('ix_appointment_status_history_changed_by'), table_name='appointment_status_history')
    op.drop_index(op.f('ix_appointment_status_history_appointment_id'), table_name='appointment_status_history')
    op.drop_index('ix_appointment_history_appointment_status', table_name='appointment_status_history')
    op.drop_table('appointment_status_history')
    op.drop_index(op.f('ix_appointment_reminders_status'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_scheduled_at'), table_name='appointment_reminders')
    op.drop_index(op.f('ix_appointment_reminders_appointment_id'), table_name='appointment_reminders')
    op.drop_index('ix_appointment_reminder_schedule', table_name='appointment_reminders')
    op.drop_table('appointment_reminders')
    op.drop_index('ix_appointments_status_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_slot_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_rescheduled_from_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index('ix_appointments_patient_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_parent_appointment_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index('ix_appointments_doctor_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_by'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_booking_source'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_type'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_waiting_list_doctor_date_status', table_name='appointment_waiting_list')
    op.drop_index(op.f('ix_appointment_waiting_list_status'), table_name='appointment_waiting_list')
    op.drop_index(op.f('ix_appointment_waiting_list_preferred_date'), table_name='appointment_waiting_list')
    op.drop_index(op.f('ix_appointment_waiting_list_patient_id'), table_name='appointment_waiting_list')
    op.drop_index(op.f('ix_appointment_waiting_list_doctor_id'), table_name='appointment_waiting_list')
    op.drop_table('appointment_waiting_list')
    op.drop_index('ix_doctor_availability_lookup', table_name='doctor_availability')
    op.drop_index(op.f('ix_doctor_availability_is_active'), table_name='doctor_availability')
    op.drop_index(op.f('ix_doctor_availability_doctor_id'), table_name='doctor_availability')
    op.drop_index(op.f('ix_doctor_availability_day_of_week'), table_name='doctor_availability')
    op.drop_table('doctor_availability')
    op.drop_index(op.f('ix_appointment_slots_slot_date'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_is_blocked'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_is_available'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_doctor_id'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_appointment_id'), table_name='appointment_slots')
    op.drop_index('ix_appointment_slot_lookup', table_name='appointment_slots')
    op.drop_table('appointment_slots')
    # ### end Alembic commands ###