"""add week6 duty doctor consultation

Revision ID: d77f135855d2
Revises: 7ceefc100cd2
Create Date: 2026-08-17 12:37:59.225136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd77f135855d2'

down_revision: Union[str, Sequence[str], None] = '7ceefc100cd2'

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=True),
    sa.Column('duty_doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('medical_assessment', sa.Text(), nullable=True),
    sa.Column('clinical_observations', sa.Text(), nullable=True),
    sa.Column('follow_up_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duty_doctor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_appointment_id'), 'consultations', ['appointment_id'], unique=False)
    op.create_index('ix_consultations_doctor_status', 'consultations', ['duty_doctor_id', 'status'], unique=False)
    op.create_index(op.f('ix_consultations_duty_doctor_id'), 'consultations', ['duty_doctor_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_index('ix_consultations_patient_status', 'consultations', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_table('case_shares',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('shared_by', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('share_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_shares_consultation_id'), 'case_shares', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_case_shares_patient_id'), 'case_shares', ['patient_id'], unique=False)
    op.create_index(op.f('ix_case_shares_shared_with_user_id'), 'case_shares', ['shared_with_user_id'], unique=False)
    op.create_index(op.f('ix_case_shares_status'), 'case_shares', ['status'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_consultation_id'), 'clinical_notes', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_doctor_id'), 'clinical_notes', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_patient_id'), 'clinical_notes', ['patient_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('diagnosed_by', sa.Integer(), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=50), nullable=True),
    sa.Column('diagnosis_name', sa.String(length=255), nullable=False),
    sa.Column('diagnosis_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnosed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_consultation_id'), 'diagnoses', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_diagnosed_by'), 'diagnoses', ['diagnosed_by'], unique=False)
    op.create_index(op.f('ix_diagnoses_patient_id'), 'diagnoses', ['patient_id'], unique=False)
    op.create_table('patient_vitals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_vitals_consultation_id'), 'patient_vitals', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_patient_vitals_patient_id'), 'patient_vitals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_vitals_recorded_by'), 'patient_vitals', ['recorded_by'], unique=False)
    op.create_table('specialist_referrals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('referred_by', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('referral_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialist_referrals_consultation_id'), 'specialist_referrals', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_specialist_referrals_patient_id'), 'specialist_referrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_specialist_referrals_specialist_id'), 'specialist_referrals', ['specialist_id'], unique=False)
    op.create_index(op.f('ix_specialist_referrals_status'), 'specialist_referrals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialist_referrals_status'), table_name='specialist_referrals')
    op.drop_index(op.f('ix_specialist_referrals_specialist_id'), table_name='specialist_referrals')
    op.drop_index(op.f('ix_specialist_referrals_patient_id'), table_name='specialist_referrals')
    op.drop_index(op.f('ix_specialist_referrals_consultation_id'), table_name='specialist_referrals')
    op.drop_table('specialist_referrals')
    op.drop_index(op.f('ix_patient_vitals_recorded_by'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_patient_id'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_consultation_id'), table_name='patient_vitals')
    op.drop_table('patient_vitals')
    op.drop_index(op.f('ix_diagnoses_patient_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_diagnosed_by'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_consultation_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_clinical_notes_patient_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_doctor_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_consultation_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index(op.f('ix_case_shares_status'), table_name='case_shares')
    op.drop_index(op.f('ix_case_shares_shared_with_user_id'), table_name='case_shares')
    op.drop_index(op.f('ix_case_shares_patient_id'), table_name='case_shares')
    op.drop_index(op.f('ix_case_shares_consultation_id'), table_name='case_shares')
    op.drop_table('case_shares')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index('ix_consultations_patient_status', table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_duty_doctor_id'), table_name='consultations')
    op.drop_index('ix_consultations_doctor_status', table_name='consultations')
    op.drop_index(op.f('ix_consultations_appointment_id'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###